project:
  type: website
  output-dir: ../docs-quarto

website:
  title: "HYDRA-EO"
  navbar:
    logo: ../assets/ESA_logo_2020_White.png   # o .svg
    left:
      - text: "Overview"
        href: index.qmd
      - text: "Pipeline"
        href: pipeline.qmd
      - text: "Tools"
        href: tools.qmd
      - text: "Docs"
        href: documents.qmd
      - text: "Timeline"
        href: timeline.qmd
    right:
      - text: "HYDRA-EO.eu"
        href: "https://hydra-eo.eu/"

format:
  html:
    theme: flatly
    css: styles.css
    toc: false
    code-copy: true
    smooth-scroll: true
    page-layout: full
    link-external-newwindow: true

